version: 1.0.{build}
configuration: Release

environment:
  TestDb: Server=(local)\SQL2016;Database=efrepositorytest;User ID=sa;Password=Password12!

services:
  - mssql2016

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore

build:
  parallel: true
  publish_wap: true
  verbosity: minimal

test:
  assemblies:
    - '**\*.Tests.dll'