version: 1.0.{build}
configuration: Release

environment:
  TestDb: Server=(local)\SQL2016;Database=efrepositorytest;User ID=sa;Password=Password12!
  SONAR_TOKEN:
    secure: ZoyNs0cPMwqpfGuk0Az0vghQNOmpHqhDNRfh4Aa8ImnNGzCPlLtHhAFW3XhW9w7y

services:
  - mssql2016

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

install:
  - cinst msbuild-sonarqube-runner

before_build:
  - nuget restore
  - MSBuild.SonarQube.Runner.exe begin /k:EFRepository /n:EFRepository /d:sonar.host.url=https://sonarqube.com /d:sonar.login=%SONAR_TOKEN% /d:sonar.cs.opencover.reportsPaths="%CD%\CodeCoverage.xml" /version:%APPVEYOR_BUILD_NUMBER%

build:
  parallel: true
  publish_wap: true
  verbosity: minimal
  project: EFRepository.sln

test_script:  
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:vstest.console.exe -targetargs:"/logger:Appveyor EFRepository.Tests\bin\Release\EFRepository.Tests.dll" -output:CodeCoverage.xml

after_test:
  - MSBuild.SonarQube.Runner.exe end /d:sonar.login=%SONAR_TOKEN%  